// Empty declarations for libraries with missing types
declare module 'babel__core' {}
declare module 'babel__generator' {}
declare module 'babel__template' {}
declare module 'babel__traverse' {}
declare module 'body-parser' {}
declare module 'bonjour' {}
declare module 'connect' {}
declare module 'connect-history-api-fallback' {}
declare module 'eslint' {}
declare module 'eslint-scope' {}
declare module 'estree' {}
declare module 'express' {}
declare module 'express-serve-static-core' {}
declare module 'graceful-fs' {}
declare module 'history' {}
declare module 'html-minifier-terser' {}
declare module 'http-errors' {}
declare module 'http-proxy' {}
declare module 'istanbul-lib-coverage' {}
declare module 'istanbul-lib-report' {}
declare module 'istanbul-reports' {}
declare module 'json-schema' {}
declare module 'json5' {}
declare module 'mime' {}
declare module 'node' {}
declare module 'node-forge' {}
declare module 'parse-json' {}
declare module 'prettier' {}
declare module 'prop-types' {}
declare module 'q' {}
declare module 'qs' {}
declare module 'range-parser' {}
declare module 'react-router' {}
declare module 'resolve' {}
declare module 'retry' {}
declare module 'semver' {}
declare module 'send' {}
declare module 'serve-index' {}
declare module 'serve-static' {}
declare module 'sockjs' {}
declare module 'stack-utils' {}
declare module 'trusted-types' {}
declare module 'ws' {}
declare module 'yargs' {}
declare module 'yargs-parser' {} 